### ISSUE TITLE
Add web interface to snapcast server

### ISSUE THREAD

**Issue by rugarci** [IVData/dockerfiles#11]
It would be nice to include this

https://github.com/badaix/snapcast-websockets-ui/blob/master/interface.html

as /www/index.html of snapserver docker image

Then adding to snapserver config

```
[http]
enabled = true
bind_to_address = 0.0.0.0
port = 1780
doc_root = /www
```
and exposing port 1780 you can open http://snapserver.local:1780 and control the streams

**Comment by hamishfagg** [comment]
It's not quite as easy as adding that file, i don't think. As the container needs a webserver to serve that file, plus websockify running too. But i will look into this

On 11 May 2020 12:08:18 AM NZST, rugarci <notifications@github.com> wrote:
>It would be nice to include this
>
>https://github.com/badaix/snapcast-websockets-ui/blob/master/interface.html
>
>as /www/index.html of snapserver docker image
>
>Then adding to snapserver config
>
>```
>[http]
>enabled = true
>bind_to_address = 0.0.0.0
>port = 1780
>doc_root = /www
>```
>and exposing port 1780 you can open http://snapserver.local:1780 and
>control the streams
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/IVData/dockerfiles/issues/11

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rugarci** [comment]
Yes it is, snapserver already has a web server

**Comment by hamishfagg** [comment]
Right you are. All done.
