### ISSUE TITLE
One snapclient getting replaced by another

### ISSUE THREAD

**Issue by gitisz** [IVData/dockerfiles#19]
Using this [Snapclient Dockerfile](https://github.com/IVData/dockerfiles/blob/master/snapclient/Dockerfile) I am seeing that when running a second, on a separate physical host, that the snapclient on the first host is replaced, making it so only one snapclient available at a time.

Start first snapclient: on Ubuntu host snapclient-0 `docker run --hostname snap0  --device /dev/snd -e HOST=snapserver.local registry.local/snapclient` 

![image](https://user-images.githubusercontent.com/4492953/108597217-e49f6d80-7355-11eb-8933-f604ae49254e.png)

Start the second snapclient on Ubuntu host snapclient-1 (a different physical machine) `docker run --hostname snap1  --device /dev/snd -e HOST=snapserver.local registry.local/snapclient` 

![image](https://user-images.githubusercontent.com/4492953/108597156-d4878e00-7355-11eb-935d-9313f64ab636.png)

Is this expected?  My understanding is to have multiple snapclients throughout the house for each amplifier to power separate multi-room speakers.

Thanks!

**Comment by gitisz** [comment]
Looks like both logs show that each snapclient has the same MAC
```
# My MAC: "02:42:ac:11:00:02"
```
```
# My MAC: "02:42:ac:11:00:02"
```

https://stackoverflow.com/questions/42946453/how-does-the-docker-assign-mac-addresses-to-containers/42947044

Adding `--mac-address 02:42:ac:11:00:03` to the docker command solves.

**Comment by hamishfagg** [comment]
It sounds like this is just a function of snapclient generating its ID based on mac. Closing since it seems like you have it sorted.
