### ISSUE TITLE
All clients merged into one 

### ISSUE THREAD

**Issue by jokerigno** [IVData/dockerfiles#2]
Hi,

I've found another intresting bug. 

The configuration work like a charm with one client. Today I added another one (another android phone with the official app) and in the app I can't see the new client.

The weird thing is that the stream work welle on the 2 phones..but they appears as one only.

Do you have the same issue?

**Comment by hamishfagg** [comment]
This is an issue with snapcast itself. See here: https://github.com/badaix/snapcast/issues/337
I'm not sure how you can fix it now with the android client, but apparently there is a fix coming.

**Comment by jokerigno** [comment]
Ok. So, issue closed.
