### ISSUE TITLE
Adding --player option to snapclient 

### ISSUE THREAD

**Issue by timbrueggenthies** [IVData/dockerfiles#20]
Hi there!
First of all, big thanks for these awesome images! Using mopidy and snapserver, setup was really easy.

I am trying to use a google home as target device, and therefore plan to add a snapclient forwarding the audio to a pipe, into forked-daapd. In the [docs](https://github.com/badaix/snapcast#client) it says that the command line option `--player` can be used to choose the output.
Could this command be added to the snapclient docker image, to be able to input as docker argument?

Thanks in advance and have a great day!
Cheers

**Comment by hamishfagg** [comment]
Hey,

Im _really_ sorry this took so long to fix. Life is always getting in the way.
I've just added an `EXTRA_ARGS` environment variable to the snapclient container, which lets you provide any arguments you'd like to snapclient.

Let me know if you have any trouble using it.
