### ISSUE TITLE
Config issues

### ISSUE THREAD

**Issue by sasgoose** [IVData/dockerfiles#21]
Hi 

I was wondering if you could help. I have done the mapping -v /some/dir:/mopidy which has created a cache folder, an empty config folder, a data folder, and a separate config file in the base directory. 

However, the container still seems to use a default config (not the config that has been created). I found this by running a console for the container and running the code "mopidy config" and the returned config is nothing like the config in the file. I have also tried editing the config that was created, restarting the container, and checking the effective config again but still no changes. How can I edit the effective config?

Cheers

**Comment by sasgoose** [comment]
So i have spent all day looking at this and I have found a lot out however it confuses me more each time. I see in the mopidy.sh for the entry looks like it is running the command to use the correct config however it doesn't seem to be picking this up

edit: if i look at the logs when I restart it records that the audio output is set to the correct value, but when I run mopidy config it says that the effective config is the default one. ie not the one that it seems to use on boot

**Comment by lukasheinz92** [comment]
Hi,

I have the same issue. I modified the _mopidy.conf_ file but when I run `mopidy config` command, I can see different configuration. Please advise.

**Comment by repole** [comment]
Was able to workaround the issue by changing the volume mapping

`- ./mopidydata:/mopidy`

to

`- ./mopidydata:/home/mopidy/.config/mopidy/`

and placing my own `mopidy.conf` in `./mopidydata`.

**Comment by hamishfagg** [comment]
Hi, sorry for being so slack in fixing this.

I've pushed an update to this repo and dockerhub that changes all of the config to /home/mopidy/.config/mopidy.

I'm not using this container right now so I'd appreciate some feedback on whether everything is working - I have tested that Iris is running, I can scan my local library and play music from it.

**Comment by lukasheinz92** [comment]
Local library is working for me too. Now I am stuck with Youtube extension - not sure if I am doing something wrong or it is a general problem.

**Comment by hamishfagg** [comment]
If you let me know what issue you're having I'll try it on my end.

**Comment by lukasheinz92** [comment]
Please see error log below:

```
ERROR    2022-02-18 20:30:26,828 [1:HttpServer] tornado.application

  Uncaught exception GET /youtube/ (192.168.0.101)

HTTPServerRequest(protocol='http', host='192.168.0.110:6680', method='GET', uri='/youtube/', version='HTTP/1.1', remote_ip='192.168.0.101')

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1704, in _execute

    result = await result

tornado.iostream.StreamClosedError: Stream is closed

[youtube] vjVkXlxsO8Q: Downloading webpage

WARNING: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

[youtube] vjVkXlxsO8Q: Downloading API JSON

ERROR: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

ERROR    2022-02-18 20:30:28,790 [1:YouTubeCoreListener-10] mopidy_youtube

  audio_url error ERROR: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))) (videoId: vjVkXlxsO8Q)
```

**Comment by sasgoose** [comment]
The local is working now, thank you so much! Although I have run into a separate problem that I thought you might be able to glance over. When I try and play a local file it immediately jumps to the next song. 

Here is what the log says:

INFO 2022-03-15 09:32:17,948 [1:HttpServer] mopidy_iris.core
Updating Snapcast stream metadata: http://192.168.1.39:1780/jsonrpc
INFO 2022-03-15 09:32:18,188 [1:HttpServer] mopidy_iris.core
Updating Snapcast stream metadata: http://192.168.1.39:1780/jsonrpc
INFO 2022-03-15 09:32:18,570 [1:HttpServer] mopidy_iris.core
Updating Snapcast stream metadata: http://192.168.1.39:1780/jsonrpc
INFO 2022-03-15 09:32:18,188 [1:HttpServer] mopidy_iris.core
Updating Snapcast stream metadata: http://192.168.1.39:1780/jsonrpc
INFO 2022-03-15 09:32:18,570 [1:HttpServer] mopidy_iris.core
Updating Snapcast stream metadata: http://192.168.1.39:1780/jsonrpc
INFO 2022-03-15 09:32:19,151 [1:HttpServer] mopidy_iris.core
Updating Snapcast stream metadata: http://192.168.1.39:1780/jsonrpc
INFO 2022-03-15 09:32:19,543 [1:HttpServer] mopidy_iris.core
Updating Snapcast stream metadata: http://192.168.1.39:1780/jsonrpc

and a little gif of what the front end does 

![307EB864-5F58-4056-B54B-1A747B5E847A](https://user-images.githubusercontent.com/44894710/158265415-dbfb9f88-3b7d-42ba-aade-4af8e589a4cc.GIF)

Has anyone seen this issue before?

**Comment by hamishfagg** [comment]
@sasgoose

> When I try and play a local file it immediately jumps to the next song.

Sorry I've just tested this with the latest build and its working fine for me so I'm not sure.
I've just pushed an update to dockerhub, maybe try that?

**Comment by hamishfagg** [comment]
@lukasheinz92 
I've tested with the new container just uploaded and adding `-e PIP_PACKAGES Mopidy-YouTube youtube-dl` and my youtube config only containing:
```
[youtube]
enabled = true
```

And I'm able to search for and play YT videos.

**Comment by sasgoose** [comment]
Thanks that does seem to have sorted the issue. After updating the log was showing an error where it couldn't open the snapfifo. after a couple of days of on and off playing I ended up restarting the snapserver and mopidy a bunch and somehow it just started working. 

Thank you so much for helping and doing these docker files. It is very cool! Also the way you have done the pip packages is super cool

**Comment by lukasheinz92** [comment]
> @lukasheinz92 I've tested with the new container just uploaded and adding `-e PIP_PACKAGES Mopidy-YouTube youtube-dl` and my youtube config only containing:
> 
> ```
> [youtube]
> enabled = true
> ```
> 
> And I'm able to search for and play YT videos.

Thank you for fixing the issue. I had used a workaround using `yt-dlp` instead of `youtube-dl` which also worked.
