### ISSUE TITLE
password for the mopidy user on the mopidy docker

### ISSUE THREAD

**Issue by siparker** [IVData/dockerfiles#22]
I tried to login via exec to install spotify and i dont know what the password is for the mopidy user on that docker?

am i missing something?

**Comment by hamishfagg** [comment]
Have you tried using the `PIP_PACKAGES` and `APT_PACKAGES` env vars? That way you wont have to do it again if the container updates.

The mopidy user is created without a password because it's not really required (unless I'm missing something). So you can't really log into that user.

**Comment by siparker** [comment]
I haven't. I am not too sure how to do that. is there a simple example?
And i also thought that the default IVdata/mopidy docker already had spotify as a default package. but it seems to not be in there for me. 
I have enabled it in the config file.

**Comment by hamishfagg** [comment]
Oh right. You would pass something like `-e PIP_PACKAGES='Mopidy-Spotify'` to your `docker run` command. But that package is installed in the container so I don't think that's your problem.

If you have a look at the logs from Mopidy starting up, it's pretty good at telling you why an extension isn't running (post the logs here if you like).

**Comment by siparker** [comment]
got it. i didnt have a username and password in the config file . the default one didnt have one so i figured it must just use the api directly. but the errors are showing clearly thats the issue. 
Now just need to figure out how to find a username and password when i login using facebook. :-)
Thanks for nudging me to the obvious answer :-)

**Comment by hamishfagg** [comment]
No worries. Let me know if it doesn't work out

**Comment by siparker** [comment]
Will do, Thanks again for the writeup and all the docker files.
