### ISSUE TITLE
Dockerfile issues with key signing in mopidy and sed command in snapcast 

### ISSUE THREAD

**Issue by dmasiel** [IVData/dockerfiles#23]
Firstly thanks for building and maintaining this. I've found it very useful. I just tried to rebuild the latest version from docker compose and have run into some issues. The first pertained to the keys associated with the mopidy apt repository. I was getting the following error:
```
 : GPG error: https://apt.mopidy.com buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78FD980E271D2943
 E: The repository 'https://apt.mopidy.com buster InRelease' is not signed.
```

I think the mopidy devs may have updated their key distribution because editing the mopidy Dockerfile according to their recommended debian install procedures solved the issue. I am pretty useless at git and am not sure if this is just an issue isolated to me so I won't make a pull request but here is what worked for me:
```
 RUN  mkdir -p /usr/local/share/keyrings && \
      wget -q -O /usr/local/share/keyrings/mopidy-archive-keyring.gpg https://apt.mopidy.com/mopidy.gpg && \
      wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list
```

The second issue actually affected me in previous versions of this repo as well. The sed command in the snapcast wget line seems to append an erroneous underscore to the URL when determining the TARGETARCH.
```
Step 5/10 : RUN  wget https://github.com/badaix/snapcast/releases/download/v${snapcast_version}/snapserver_${snapcast_version}-1_$(echo $TARGETARCH | sed 's/arm/armhf/g').deb
 ---> Running in 2b5ddfaab4c7
--2022-03-24 05:13:04--  https://github.com/badaix/snapcast/releases/download/v0.26.0/snapserver_0.26.0-1_.deb
```
I have just been manually entering the appropriate URLs for this and again the error could be on my side but I thought it was worth mentioning.

Edit: It turns out I just didn't realize that I needed to set the definition of the TARGETARCH variable in the dockerfile and when I did so it worked out fine

**Comment by hamishfagg** [comment]
Thanks for this report.
I've updated the dockerfile to include your updated mopidy install method. And yeah, the target arch needs to be there. I should probably add a default..

Thanks again
