### ISSUE TITLE
Entrypoint for Snapclient not substituting variables

### ISSUE THREAD

**Issue by D3v01dZA** [IVData/dockerfiles#25]
In the latest snapclient release the ENTRYPOINT command was changed to add EXTRA_ARGS.

Unfortunately it doesn't seem that any variable substitution is working for the new way you are specifying ENTRYPOINT (see https://stackoverflow.com/questions/37904682/how-do-i-use-docker-environment-variable-in-entrypoint-array).

This shows up on my config as 

2022-05-09 14-15-09.188 [Error] (Controller) Exception: BrowseAvahi - Failed to create client: Daemon not running

which is where snapcast is trying to connect to the server via avahi/mdns, which for some reasons I don't have running/don't want to run.

Thanks for taking a look!

**Comment by D3v01dZA** [comment]
If anyone else had this issue you can override the entrypoint temporarily using compose or the cli to 'snapclient -h <HOST>'

**Comment by hamishfagg** [comment]
thanks for this. I was wondering why that error popped up.
I've pushed a fix and am rebuilding the containers now.
