### ISSUE TITLE
ytmusic error

### ISSUE THREAD

**Issue by keesfluitman** [IVData/dockerfiles#27]
I had it working once, but now I had to get it back up and running because spotify stopped support.

My error is:
 Disabled extension ytmusic: ytmusicapi<0.21.0,>=0.20.0 required, but found ytmusicapi 0.22.0 at /home/mopidy/.local/lib/python3.7/site-packages

What would you suggest I do?

**Comment by hamishfagg** [comment]
I've just pushed an update that I've checked installs ytmusicapi 0.20.0 so it should work. It successfully refreshes my YT playlists. Let me know how it goes.
