### ISSUE TITLE
Installation problem...

### ISSUE THREAD

**Issue by bw118** [IVData/dockerfiles#30]
Hello,
I followed the README.md in : https://github.com/IVData/dockerfiles/tree/master/mopidy-multiroom

And found out that it is not working... I had to map an additional volume as explained in this other README.md: https://github.com/IVData/dockerfiles/tree/master/mopidy (and also here: https://hub.docker.com/r/ivdata/mopidy )

You might want to modify your README.md in : https://github.com/IVData/dockerfiles/tree/master/mopidy-multiroom accordingly?

Great work! TY!

**Comment by bw118** [comment]
Also, there is no default config to restart the container unless stopped... Is it on purpose?

**Comment by hamishfagg** [comment]
Good catch.
This was because this compose file is very old :) and the mopidy data folder has changed locations in the mopidy container. I've fixed the compose file now.

I've also made all of the containers restart 'unless stopped'.

Thanks!

**Comment by bw118** [comment]
Thank you!
