### ISSUE TITLE
Snapserver ports

### ISSUE THREAD

**Issue by lukasheinz92** [IVData/dockerfiles#31]
Hello,
I am not able to run snapserver with published ports. There is an error below (Portainer).

```
failed to deploy a stack: Container mopidy Running Container snapserver Starting Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:1704 -> 0.0.0.0:0: listen tcp 0.0.0.0:1704: bind
```

**Comment by hamishfagg** [comment]
At first glance that seems to be trying to bind to port 0 on 0.0.0.0 which seems weird.
I've never used portainer, so I'm not sure how to help here.

**Comment by lukasheinz92** [comment]
It started to work, not sure what the problem was :)
