### ISSUE TITLE
Snapweb has gone missing

### ISSUE THREAD

**Issue by negimeister** [IVData/dockerfiles#33]
It seems that the current image is missing the files for the Web UI. It worked until a few days or weeks ago, but now I get a message saying `The resource '/' was not found.` when trying to access it.  
According to the config, the files should be in `/usr/share/snapserver/snapweb` but the snapserver directory doesn't exist.

**Comment by hamishfagg** [comment]
Yeah sorry about that. I've just pushed another update that will fix this.
