### ISSUE TITLE
Question about snapserver config

### ISSUE THREAD

**Issue by ovizii** [IVData/dockerfiles#37]
I've mapped your default snapserver.config and was looking at https://raw.githubusercontent.com/badaix/snapcast/master/server/etc/snapserver.conf for what parameters are available, but can't seem to figure out what this is meant to do:

```
[stream]                                                                                                                                             
stream = tcp://0.0.0.0?name=Snapserver
```

Your README says:

```
Config
You can overwrite snapcast's config by mounting a file to /etc/snapserver.conf in the container. The default settings create a single stream called "Snapserver" which listens on a TCP socket on port 4953 (this was previously a fifo), and enables [SnapWeb](https://github.com/badaix/snapweb) on port 1780. See the [Snapcast docs](https://github.com/badaix/snapcast/blob/master/doc/configuration.md) to create your own config.
```
Does this relate the above stream? 
I'm confused about why the snapserver should listen on a TCP socket on port 4953 – this port is not mentioned in your compose files nor did I figure out what for this server would listen on this port?

Could you please shed some light onto this

**Comment by hamishfagg** [comment]
Hi there,

Thats how audio data makes it from Mopidy to Snapcast - Snapserver listens on that tcp socket and mopidy connects to it, and sends audio data through.

Hope that helps :)

**Comment by ovizii** [comment]
Seems obvious in retrospective :-) thanks for being kind in my blonde moment.
