### ISSUE TITLE
Update snapcast to 0.19.0

### ISSUE THREAD

**Issue by hawkeye217** [IVData/dockerfiles#6]
0.19.0 has some nice goodies including TCP streams. Would be great to have an updated container.

Thanks!

**Comment by hamishfagg** [comment]
Sure thing!
I haven't been using Snapcast for a long time so please let me know if anything else in this container is out of date. I'm worried the configuration etc is dated.

Just sat down so I'll look at updating now

**Comment by hawkeye217** [comment]
Great, thanks!  Regarding the configuration, the Snapcast author moved to a ``snapserver.conf`` file a while ago (in ``/etc/``), though it's still possible to specify ``SNAPSERVER_OPTS`` in ``/etc/default/snapserver``.

**Comment by hamishfagg** [comment]
Hey,

I don't really have the time to sort the config now, but the 0.19 images should be up now, and I'll create a new issue to remind me to do the config changes

**Comment by hawkeye217** [comment]
No problem. I pulled your updated image and it's working great. Thanks!
